# Generated by Django 5.2 on 2026-05-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.TextField()),
                ('url_hash', models.CharField(blank=True, db_index=True, default='', max_length=64, unique=True)),
                ('short_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('encrypted_data', models.TextField(blank=True, null=True)),
                ('access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['url_hash'], name='short_short_url_has_fa2002_idx'), models.Index(fields=['short_code'], name='short_short_short_c_a0d3f8_idx'), models.Index(fields=['-click_count'], name='short_short_click_c_6e0675_idx'), models.Index(fields=['created_at'], name='short_short_created_6450a4_idx'), models.Index(fields=['is_active'], name='short_short_is_acti_dcd711_idx')],
            },
        ),
    ]
